version: '3.4'

networks:
  dev:
    driver: bridge

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: api
    ports:
      - 5058:5058
    depends_on:
       db:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=api;Uid=api;Pwd=123456;
    networks:
      - dev
    volumes:
      - ./src:/app/src


  db:
    build:
      context: .
      dockerfile: docker/Dockerfile.db
    container_name: db
    command: --lower_case_table_names=1
    environment:
      MYSQL_DATABASE: api
      MYSQL_USER: api
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
      - ./db-data:/var/lib/mysql:z
    # https://github.com/docker/compose/issues/9367
    healthcheck:
      test: "mysql -uroot -p$$MYSQL_ROOT_PASSWORD"
      interval: 10s
      timeout: 30s
      retries: 3
    networks:
      - dev

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - dev

volumes:
  db-data:










